using Metamon.Combat.Abilities;
using Metamon.Combat.Damage;
using Metamon.Combat.State;
using Metamon.UI;

namespace Metamon.Combat
{
    public static class FighterFactory
    {
        public enum FighterType
        {
            EGG,
            TADPOLE,
            FROG,
            FISH,
            SNAKE,
            BANKER
        }

        public static Fighter CreateFighter(FighterType type)
        {
            return type switch
            {
                FighterType.EGG => EggFighter(),
                FighterType.TADPOLE => TadpoleFighter(),
                FighterType.FROG => FrogFighter(),
                FighterType.FISH => FishFighter(),
                FighterType.SNAKE => SnakeFighter(),
                FighterType.BANKER => BankerFighter(),
                _ => EggFighter(),
            };
        }

        private static Fighter FrogFighter()
        {
            var state = new FighterState(
                "Frog",
                new HealthAttributes { CurrentHealth = 30 },
                new AttackAttributes { Strength = 4, Agility = 5 },
                new DefenceAttributes { MaxHealth = 30, Armor = 2, IceRes = 1 }
            );

            var abilities = new Ability[]
            {
                new("Leap Strike", "", 1, [new PhysicalDamage { Amount = 6 }]),
                new("Croak", "", 2, [new EventDamage{OnDeal = (s, t) => DuelDrawer.WriteToBattleLog("Croak")}]),
                new("Water Kick", "", 1, [new PhysicalDamage { Amount = 4, FlatArmorPen = 1 }]),
                new("Morph", "", 10, [])
            };

            return new Fighter(state, FROG_IMAGE, abilities);
        }

        private static Fighter TadpoleFighter()
        {
            var state = new FighterState(
                "Tadpole",
                new HealthAttributes { CurrentHealth = 15 },
                new AttackAttributes { Strength = 2, Agility = 12 },
                new DefenceAttributes { MaxHealth = 15, Armor = 0, IceRes = 1 }
            );

            var abilities = new Ability[]
            {
                new("Wiggle Dash", "A rapid dart to evade and reposition.", 1),
                new("Tail Flick", "A quick slap of the tail.", 1, [new PhysicalDamage { Amount = 3 }]),
                new("Murk Cloud", "Stir up silt to obscure vision.", 2), // Placeholder for blind/debuff
                new("Slipstream", "Speed boost for the next turn.", 2) // Could apply a FighterStateMod
            };

            return new Fighter(state, TADPOLE_IMAGE, abilities);
        }

        private static Fighter EggFighter()
        {
            var state = new FighterState(
                "Egg",
                new HealthAttributes { CurrentHealth = 5 },
                new AttackAttributes { },
                new DefenceAttributes { MaxHealth = 5, Armor = 0 }
            );

            var abilities = new Ability[]
            {
                new("Wiggle Dash", "A rapid dart to evade and reposition.", 1),
                new("Tail Flick", "A quick slap of the tail.", 1, [new PhysicalDamage { Amount = 3 }]),
                new("Murk Cloud", "Stir up silt to obscure vision.", 2), // Placeholder for blind/debuff
                new("Slipstream", "Speed boost for the next turn.", 2) // Could apply a FighterStateMod
            };

            return new Fighter(state, EGG_IMAGE, abilities);
        }

        private static Fighter SnakeFighter()
        {
            var state = new FighterState(
                "Snake",
                new HealthAttributes { CurrentHealth = 35 },
                new AttackAttributes { Strength = 5, Agility = 6 },
                new DefenceAttributes { MaxHealth = 35, Armor = 2 }
            );

            var abilities = new Ability[]
            {
                new("Bite", "A venomous bite.", 1, [new PhysicalDamage { Amount = 6, PercentageArmorPen = 10 }]),
                new("Constrict", "Wrap and squeeze (placeholder).", 2),
                new("Hiss", "Intimidates the opponent (placeholder).", 2),
                new("Slither Strike", "Hit and back off.", 1, [new PhysicalDamage { Amount = 4, FlatArmorPen = 2 }])
            };

            return new Fighter(state, SNAKE_IMAGE, abilities);
        }

        private static Fighter CrazyFrogFighter()
        {
            var state = new FighterState(
                "Crazy Frog",
                new HealthAttributes { CurrentHealth = 45 },
                new AttackAttributes { Strength = 6, Agility = 7 },
                new DefenceAttributes { MaxHealth = 45, Armor = 3 }
            );

            var abilities = new Ability[]
            {
                new("CHAOS PUNCH", "A wild unpredictable strike.", 1, [new PhysicalDamage { Amount = 8, PercentageArmorPen = 20 }]),
                new("Lick Zap", "Magical tongue with electric spark.", 2, [new ArcaneDamage { Amount = 4, WisdomScaling = 0.5f }]),
                new("Ribbit Slam", "Hits everyone (placeholder).", 3),
                new("Evade!", "Boost agility (placeholder).", 2)
            };

            return new Fighter(state, CRAZYFROG_IMAGE, abilities);
        }

        private static Fighter BankerFighter()
        {
            var state = new FighterState(
                "Banker",
                new HealthAttributes { CurrentHealth = 40 },
                new AttackAttributes { Intellect = 6, Wisdom = 5 },
                new DefenceAttributes { MaxHealth = 40, Armor = 1, ArcaneRes = 5 }
            );

            var abilities = new Ability[]
            {
                new("Audit Beam", "Destroys financial irregularities.", 2, [new ArcaneDamage { Amount = 7, WisdomScaling = 1f }]),
                new("Paper Shield", "Raises armor temporarily (placeholder).", 3),
                new("Fine Print", "Debuffs enemy (placeholder).", 2),
                new("Cash Smash", "Throw coins at the enemy.", 1, [new PhysicalDamage { Amount = 5 }])
            };

            return new Fighter(state, BANKER_IMAGE, abilities);
        }

        private static Fighter FishFighter()
        {
            var state = new FighterState(
                "Predator Fish",
                new HealthAttributes { CurrentHealth = 50 },
                new AttackAttributes { Strength = 8, Agility = 4 },
                new DefenceAttributes { MaxHealth = 50, Armor = 3 }
            );

            var abilities = new Ability[]
            {
                new("Bite", "A vicious snap with razor-sharp teeth.", 1, [new PhysicalDamage { Amount = 10, FlatArmorPen = 2 }]),
                new("Feeding Frenzy", "Strike repeatedly in a flurry of bites.", 3, [new PhysicalDamage { Amount = 4, PercentageArmorPen = 25 }]),
                new("Blood Scent", "Deal extra damage to already injured enemies (placeholder).", 2),
                new("Fin Charge", "Ram the target with armored fins.", 2, [new PhysicalDamage { Amount = 6, FlatArmorPen = 1, PercentageArmorPen = 10 }])
            };

            return new Fighter(state, "🦈", abilities);
        }

        private static readonly string FROG_IMAGE = @"
--------------------------------------------------
--------------------------------------------------
--------------------------------==----------------
------------------------------*******=------------
---------------------------=+***@%***+**#*=-------
----------------------=******++*##**********=-----
-----------------=+*****##******************=-----
--------------*#++*%#%*%%+**************##*-------
-----------+*********+*##*******=======+=---------
---------**#######%#**#%##*#*+======*=------------
-------#******+********#++========+=--------------
-----*#*#**###***#*+=============+=---------------
----=#**********++**+========*===#----------------
-----+#*#*#*++++++++++++*+===#===*+++++-----------
-----=******+++++++*+***+++*=-+===++**+=----------
-----=*************#*+*+#+----====+++**=----------
-------+**#***#*#****#*--------+====**+=----------
-------------#**##***+*+=--------*==+**=----------
-------------=++****+++*=----------==++=----------
--------------------------------------------------".Trim();

        private static readonly string TADPOLE_IMAGE = @"
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
...........:::::..................................
......:X+++;++xx+x+;;;:::+Xx;:::;;+++;:...........
....;+;;++x+;++++++x+xx++xxxx++;:::::::;;;+;;::;+:
...+;++xX&$+;++;++++x++++x+++++x++++++x+XX+xxX;+;.
..+;;;++++++++++xx+++xxXXx;;++;++;++;:;x+::::.....
..;++xx+++x+x++x++x+x:::::;;:+xx+++;..............
....:+Xx++x++x++xX+++XxxX;........................
.................+xxx+;;+:........................
.....................+++..........................
..................................................
..................................................
..................................................
..................................................
..................................................".Trim();

        private static readonly string EGG_IMAGE = @"
 ..................................................
................:::.:::::..:::::::................
...............:...:;;::;::...::::::..............
..............::::+xXX+;;::.;+xXx;;;:.............
..............:::;xXX$X;;:::+xXXX+;+;.............
...............::;+xx+;;;:::+XXXx;;;:.............
...........:...:::;;;;;:::::::;;;;;:::............
.........:...:;;;;;;::::::::::;;;:...::::.........
.........::;xxxXX+;;::..::;:::;:...;++;;;;........
.........:;;xxXX$+;::.:;xXX+;:;:::+xxXXx;+:.......
.........:::;xXx++;:::;xxXXX;;;::;xX$$$+;;........
..........::::;;;;;::::;xx+;;;;::::;++;;;:........
............::::..:::::::;;;;;::::::;;:...........
............::...:::::;::::::::::::::.............
...........::::;+xx+;:;::::.:;+xX+;:;;............
...........:::;xxXXX+;;;:;::;xxXXX+;;;............
...........:;:;x$$$X;;;;::::;xXXXx;;;.............
............::::;;;;;;;:.::::;;;;;;;:.............
..............:::;;;;::....:::::::................
..................................................".Trim();

        private static readonly string CRAZYFROG_IMAGE = @"
..................................................
..................................................
.........;+;......:...............................
........XxxXxxx::..;$::XXX$$Xx:............:;+;...
........:x;...::...:$XX$x;;xXX$:....+x++;;+++xxx..
...............:X$$$+;xXXXXX$&$$:.x+;.....+xxx$+..
...............:x++xxXXXX$$$$$$$X$$+..............
...............++.$xx;+$$XXxXXX&$X;...............
..............:Xx+;++xxx;X+;;XX$$&+...............
..............:x;;::.::;xxxxxx+X$$$:..............
..............+;;:X$+xx;;+xxx$XX&$$$x.............
..............X;:::::::::::;+x$&;;$$$:............
..............+.:x+xX$$$$$&$$XXX++.+;.............
....................xx$XXXxxXX$$$X::X;:...........
..................;+$X;XXXXxXX$X;;..::............
.................;X+:..:;xx+;:.x$Xx...............
............::;++x+.............:+Xx..............
...........:xxX+...................;:.............
...................................;::::..........
...................................;++;+:.........".Trim();

        private static readonly string BANKER_IMAGE = @"
..................................................
.................:++:..x$X:.......................
...............:$&&X+:.+&&+.......................
...............$&&&$X+.;&&+.......................
...............x&&&&$X+:x$+..:....................
................;X&&$x+:.:x+&&:...................
.................:X++xx+:X&$$&:...................
................+&&XxX$&X$$+..&+..................
................X&&&&+........&X..................
..................x&$;:::.;:X+.+X;................
.................:xx;::.:..:...x;.................
..................+x;..:;;;x..:+;.................
..................:;:....;;....x:.................
.................x$$x+:..:....:+$$X;..............
..............:X&XxX+$&&X;;;:;;;+;:+X+:...........
..........;$$x++X;xX;+X&$$xx$X.X&&$X$x+;;:........
........;$$&X&$$X&&&X;&&x$$&&$:&&&&x&&&X$$;.......
........X:$&$&&&&$$&&;.. ...  &&&$$&&&&&$&&;......
.......+X;&&X&&&&&&$&x.  .. .x&&$$$&&&&&$&&X......
.......:x;&&x&&&&x&&&&.. .. ;&&&&$&&$Xx$X&&$:.....".Trim();

        private static readonly string SNAKE_IMAGE = @"
..................:+;;;;;;;;++x;;;;;+;............
................;;;;;;;;;;;;;;;+;;;;;;;+:.........
.............+X;;;;;;+++;;;;;;;;X;;;;;;;;;........
...........;;;;;;;++;;;++;;;;;;;;;;;;;;;;;+.......
..........:;;;;;;x;:;x::+;...+::;;;;;;;;;;;+......
..........+;;;;;;x;;+x;;+:..:;..:.:;;;;;;;;;:.....
.......:;;;;;;;;;;;;;;;:..::;:;:::..:;;;;;;+:.....
.......+;;;;;+;;;;;;+;.:;;X::;.:X:...+;;;;;+:.....
.......;;;++;;+;;:+++xx+:;::..;;::.:..+;;;;;:.....
........:.;..:.::x++++;+;+;.::+:::...:;;;+;+......
.........;;:..+:+++;+;;+:;+::+:::....+;;;+x.......
...........;...+x;;+;;x:+:.:;::.::..;;;;++........
..............x+;X;;+;X..:+::......x;;++x:........
..............+XXx+++:.:;:....::.+;;;++;..........
....;xxXXXXXxx+:......::.......+;;;++x:...........
......+X;:..........:;.:::;..;;;;+++:.............
.....:;............;:......:+;;++++...............
..................;:......;;;;++;;................
..................:.::::::+;;+++;.................
..................+......x;;;+++..................".Trim();

        private static readonly string FISH_IMAGE = @"
..................................................
..............................::;;;;:.............
.................;++:.....;$x+xxxX$;..............
............;+x+xxXXXxxxXXXxxxxxXx................
.........:+x+xxXx:$xxxXxxxXxxXXXX:...........::::.
......;xx+x$$+.:+x+xxX;XxxxxxxxXX+.........xxxxXXX
..;+x+++++xxxxXx++XX:x;+xxxxXxxxxX;......+x+xXXx..
xx++++++++xXx:::;x+;:x;+xxXXxxxxxxxX....:x+xXXx...
.;+:::::;x+::;xxX+;+;x;+xxxxxxxxxxxxX:.;XxxxXX;...
...:Xx++++xX++..:;..:;;XxxxxxxxxxxxxxxxxxXxXX+....
....:+..+::..+x::.;:;;;xxxxxxxxxxxxxxxxxxxxXxx:...
......;.;$+..;:..+x$;:Xxxxxxxxxxxx$+x:..:XxxXx;...
........+x.:$+x:::x;::;xxxxxxX$X$.........+$xXX:..
..........+:..:+x;:::::xxxxx+xxx:.................
..........:+++;;;::::::;;Xxxxxxx$:................
.............:;xXx++xXx;::+$XXXxxX$:..............
...................:xxx.......::..................
..................................................
..................................................
..................................................".Trim();
    }
}